### ISSUE TITLE
Things to do for control object

### ISSUE THREAD

**Issue by drfinlayscott** [iagomosqueira/FLasher#10]
Before dispatch to C++:
Add a 'timestep' column that translates the year / season columns to the timestep.
Check that the timesteps are consecutive
Add 'biol' column for targets that relate to biols
Add a 'target' column (integer, consecutive, starting from 1). 'target' is used to identify which targets are to be processed together, i.e. multiple rows can have the same 'target' value (they are simultaneous targets).
Add the 'FCB' integer matrix as a slot to object@target. This is a map that describes what FLFishery / FLCatch combination catches which FLBiol. It is n x 3 with colnames c('F', 'C', 'B'). The values are integer describing the positions of the FLFishery etc within the lists that are based to the C++ side. See examples for more detail.

**Comment by iagomosqueira** [comment]
On 30/03/15 15:39, Finlay Scott wrote:
> Before dispatch to C++ add a 'timestep' column that translates the year / season columns to the timestep.
> Check that the timesteps are consecutive
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/iagomosqueira/FLasher/issues/10
> 

I will add it. We have code for this already in as.data.frame(FLQuant).


Iago

**Comment by drfinlayscott** [comment]
Most issues dealt with. We have moved on...
