### ISSUE TITLE
RCpp Flasher plugin might not work in Windows

### ISSUE THREAD

**Issue by iagomosqueira** [iagomosqueira/FLasher#17]
This line (R/rcpp_plugin.R, line 6) has

FLasher.so_location <- paste(.libPaths()[1], "/FLasher/libs/FLasher.so",sep="")

but this should not work in Windows, it will at least need to use

'FLasher.dll'

We need to find out how to make this cross-platform

**Comment by drfinlayscott** [comment]
That is true. I added the plugin as an experiment then sort of forgot about
it. We can take a look at RcppArmadillo which is where I copied the code
from.

**Comment by iagomosqueira** [comment]
RcppArmadillo has (R/inline.R)

inlineCxxPlugin <- Rcpp:::Rcpp.plugin.maker(
	include.before = "#include <RcppArmadillo.h>", 
	libs           = "$(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)", 
	package        = "RcppArmadillo"
)

but I cannot find where $FLIBS is being set

**Comment by drfinlayscott** [comment]
Is FLIBS what we are looking for? Is that the library directory?

**Comment by drfinlayscott** [comment]
(quick google) FLIBS is where Fortran libs are. Not much use for us

**Comment by iagomosqueira** [comment]
Let's try with

  FLasher.so_location <- paste0(find.package('FLasher'), "/libs/FLasher", .Platform$dynlib.ext)

Let me try in both platforms. Should it compile with gcc?

**Comment by drfinlayscott** [comment]
It should do... The C++11 flags are set as R Flags rather than compiler
specific flags.

**Comment by drfinlayscott** [comment]
Bit hacky but fixed for now
