### ISSUE TITLE
Change ssb method for FLBiol to srp

### ISSUE THREAD

**Issue by iagomosqueira** [iagomosqueira/FLasher#18]
For consistency, the ssb method for FLBiol, both bin FLasher and FLCore, should be called srp, spawning reproductive potential.

**Comment by drfinlayscott** [comment]
Sure I can change that later.

My problem is that stupid devtools I used to get with g++, but not with
clang, now also happens with clang. My dev process is broken again...

**Comment by drfinlayscott** [comment]
Except looking at the compilation messages, R is using g++ again, not
clang. Problem solved.

**Comment by drfinlayscott** [comment]
Still just uses the 'normal' SSB calculation for now
