### ISSUE TITLE
Implement FLQuant %*% operators in Cpp

### ISSUE THREAD

**Issue by iagomosqueira** [iagomosqueira/FLasher#19]
The %*%, %/%, %+% and %-% operators for FLQuant are able to extend one dimension of length one in one object to the length in the other. They could  be very useful in Cpp.

To be done in the near future

**Comment by drfinlayscott** [comment]
Sure. I'm sure you'll figure out a clean way of adding them ;)

**Comment by drfinlayscott** [comment]
Not possible.  %*% etc are not existing C++ operators
